TOKEN = 'YOUR DISCORD API TOKEN HERE'

OWNER_ID = 'OWNER DISCORD ID HERE'
DB_PATH = 'cakebot.db'

PRIVILEGED_INVITE_LINK  = 'DISCORD INVITE LINK HERE'
NORMAL_INVITE_LINK = 'DISCORD INVITE LINK HERE'

MUSIC_SEARCH_RESULT_TIME = 12
